# Generated by Django 4.1.6 on 2023-02-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='period_time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='serial',
            name='period_time',
            field=models.FloatField(),
        ),
    ]
