# Generated by Django 4.1.6 on 2023-02-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_film_slug_alter_film_quality_alter_film_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='type',
        ),
        migrations.AddField(
            model_name='film',
            name='is_movie',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='is_serial',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('ماجراجویی', 'ماجراجویی'), ('عاشقانه', 'عاشقانه'), ('درام', 'درام'), ('اکشن', 'اکشن'), ('مستند', 'مستند')], max_length=150),
        ),
    ]
