# Generated by Django 4.1.6 on 2023-02-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_remove_film_type_film_is_movie_film_is_serial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
