# Generated by Django 4.1.6 on 2023-02-07 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repository', '0005_delete_command'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('is_sub_command', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('film', models.ManyToManyField(related_name='command', to='repository.film')),
                ('sub_command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.command')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
