# Generated by Django 4.1.6 on 2023-02-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_command_sub_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='text',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
